import Navbar from "@/components/shared/Navbar";
// import { Inter } from "next/font/google";
import "./globals.css"
import TitleBar from "@/components/shared/TitleBar";



// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TitleBar></TitleBar>
        <Navbar></Navbar>
        
        {children}
        </body>
    </html>
  );
}
